### ISSUE TITLE
Add http prefix to Builder API retryOptions

### ISSUE THREAD

**Issue by AliSoltanianFJ** [AliSoltanianFJ/azsdk-java-rewrite-recipes-fork#4]

**Comment by stoatus-quo** [comment]
http prefix added to inherited method retryOptions in TextTranslationClientBuilder ONLY!
This is NOT adequate! `implements HttpTrait` should be targeted in its entirety.
A set of recipes to switch from `com.azure.core.client.traits.HttpTrait` to `io.clientcore.core.models.traits.HttpTrait` should be chained together.

**Comment by stoatus-quo** [comment]
Possible approach:
Locate with FindImplementations (and extract method pattern)
Update import statement with ChangeType (currently not recognising path, but should work)
Update all method names 
Chain with any management file recipes, eg dependecies.
