### ISSUE TITLE
Refactor HttpTrait Test to Test Builder Code

### ISSUE THREAD

**Issue by AliSoltanianFJ** [AliSoltanianFJ/azsdk-java-rewrite-recipes-fork#80]
From the Microsoft Engineers (see [PR 14](https://github.com/Azure/azsdk-java-rewrite-recipes/pull/14/files/5447e27b96a32983846088fe796effd5c4256353#diff-7a6cbf8eddb50a0593bbb3f0b36d80eb6bde0707a26649a5f646f13b07cb2a24)):

> Users generally don't implement traits. We should test how the builder code is transformed by the recipes. For e.g. clientBuilder.addPolicy(new HttpPipelinePolicy(){...}) is transformed to clientBuilder.addHttpPipelinePolicy(new HttpPipelinePolicy(){...})

Need to refactor HttpTrait tests to test how builder code is transformed

**Comment by stoatus-quo** [comment]
As the cause of this problem, I'm happy to fix it.

**Comment by stoatus-quo** [comment]
Most HttpTrait methods and params implemented by TextTranslationClientBuilder are migrated to the v2 version.
Tests cover client usage of the builder Api. 
clientOptions and httpRedirectOptions are not covered.
